name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CI: true
  REACT_APP_API_PUBLIC_KEY: ${{ secrets.REACT_APP_API_PUBLIC_KEY }}
  REACT_APP_API_PRIVATE_KEY: ${{ secrets.REACT_APP_API_PRIVATE_KEY }}
  REACT_APP_API_URI: ${{ secrets.REACT_APP_API_URI }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: yarn

      - name: test
        run: yarn test

      - name: build
        run: yarn build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: ./build